name: Connect Four Game

on:
  issues:
    types: [opened]

jobs:
  play:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - name: Play Connect Four
        uses: ThomasGuillot/connect-four-readme@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
